/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/Virksomhet": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["VirksomhetOutputDto"][];
            "application/json": components["schemas"]["VirksomhetOutputDto"][];
            "text/json": components["schemas"]["VirksomhetOutputDto"][];
          };
        };
      };
    };
    put: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VirksomhetEditDto"];
          "text/json": components["schemas"]["VirksomhetEditDto"];
          "application/*+json": components["schemas"]["VirksomhetEditDto"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VirksomhetInputDto"];
          "text/json": components["schemas"]["VirksomhetInputDto"];
          "application/*+json": components["schemas"]["VirksomhetInputDto"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
  "/Virksomhet/{id}": {
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Adresse: {
      /** Format: int32 */
      id: number;
      adresselinje_1: string;
      adresselinje_2?: string | null;
      /** Format: int32 */
      postnummer: number;
      poststed: string;
    };
    AdresseInputDto: {
      adresselinje_1?: string | null;
      adresselinje_2?: string | null;
      /** Format: int32 */
      postnummer?: number;
      poststed?: string | null;
    };
    VirksomhetEditDto: {
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      organisasjonsnummer: number;
      navn: string;
      adresse: components["schemas"]["AdresseInputDto"];
      telefon: string;
      epost: string;
    };
    VirksomhetInputDto: {
      /** Format: int32 */
      organisasjonsnummer: number;
      navn: string;
      adresse: components["schemas"]["AdresseInputDto"];
      telefon: string;
      epost: string;
    };
    VirksomhetOutputDto: {
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      organisasjonsnummer: number;
      navn: string;
      telefon: string;
      adresse: components["schemas"]["Adresse"];
      epost: string;
      underAvvikling?: boolean | null;
      konkurs?: boolean | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
